# Generated by Django 5.2.8 on 2025-12-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_status_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='posts',
            new_name='post',
        ),
    ]
