# Generated by Django 5.2.8 on 2025-12-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_media_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
    ]
