# Generated by Django 5.2.8 on 2025-12-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
